import { Link } from "@tanstack/react-router";
import { ArrowRight, Bot, Check, Database, Network, Quote, ShieldCheck, Sparkles, Workflow, Zap } from "lucide-react";
import { SiN8N, SiSupabase, SiGooglesheets, SiWhatsapp, SiMeta, SiZapier, SiMake } from "react-icons/si";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { assets, faqs, products, projects, services } from "@/lib/flowpilot-data";
import { ProductCard, ProjectCard } from "./cards";
import { SectionHeading } from "./site";
import { serviceIcons } from "./icons";

export function HomePage(){return <>
<section className="min-h-[760px] bg-accent/30 px-3 pb-10 pt-24 sm:px-5"><div className="mx-auto grid min-h-[650px] max-w-7xl gap-3 lg:grid-cols-[1.08fr_.92fr]"><div className="flex flex-col justify-center rounded-xl border border-border bg-background p-7 sm:p-12 lg:p-16"><div className="mb-6 flex w-fit items-center gap-2 rounded-[4px] border border-primary/20 bg-accent px-3 py-2 text-xs font-semibold text-accent-foreground"><Sparkles className="h-4 w-4"/> AI automation for growing businesses</div><h1 className="max-w-2xl text-5xl font-semibold leading-[1.04] sm:text-6xl lg:text-7xl">Automate Your Business. <span className="text-primary">Work Smarter</span> with AI.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-muted-foreground">I design AI agents and connected workflows that remove repetitive work, respond faster and keep your operations moving.</p><div className="mt-8 flex flex-wrap gap-3"><Button size="lg" asChild><Link to="/contact">Start a Project <ArrowRight/></Link></Button><Button size="lg" variant="outline" asChild><Link to="/projects">View My Work</Link></Button></div><div className="mt-10 flex flex-wrap items-center gap-5 border-t border-border pt-6 text-sm"><span className="flex items-center gap-2 font-semibold"><ShieldCheck className="h-5 w-5 text-primary"/> 50+ workflows delivered</span><span className="text-muted-foreground">Built with clear logic, testing and human handoff.</span></div></div><div className="relative min-h-[500px] overflow-hidden rounded-xl bg-workflow"><img src={assets.founder} alt="Md. Sabbir Hossain, FlowPilot AI automation specialist" className="h-full w-full object-cover object-center"/><div className="absolute left-4 top-6 float-slow rounded-lg border border-footer-border bg-footer/90 px-4 py-3 text-footer-foreground shadow-lg backdrop-blur"><span className="text-xs text-footer-muted">Automation stack</span><strong className="mt-1 flex items-center gap-2 text-sm"><Network className="h-4 w-4 text-primary"/> AI Agent → n8n → APIs</strong></div><div className="absolute bottom-7 right-4 float-slow rounded-lg border border-footer-border bg-footer/90 p-4 text-footer-foreground shadow-lg backdrop-blur [animation-delay:1s]"><div className="grid grid-cols-3 gap-3 text-center text-xs"><span><Bot className="mx-auto mb-1 text-primary"/>AI</span><span><Workflow className="mx-auto mb-1 text-primary"/>n8n</span><span><Database className="mx-auto mb-1 text-primary"/>Data</span></div></div></div></div></section>
<TechStrip/><section className="section-band"><div className="site-container"><SectionHeading eyebrow="Services" title="Automation for the work that slows you down" description="From one focused workflow to a connected operating system, every build starts with your real process." action={<Button variant="outline" asChild><Link to="/services">All services <ArrowRight/></Link></Button>}/><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{services.map(([icon,title,desc])=>{const Icon=serviceIcons[icon as keyof typeof serviceIcons];return <article key={title} className="group rounded-xl border border-border bg-card p-6 shadow-card transition-all hover:-translate-y-1 hover:border-primary/50 hover:shadow-card-hover"><div className="grid h-11 w-11 place-items-center rounded-lg bg-accent text-primary transition-transform group-hover:-translate-y-1"><Icon/></div><h3 className="mt-5 text-xl font-semibold">{title}</h3><p className="mt-2 leading-7 text-muted-foreground">{desc}</p></article>})}</div></div></section>
<HowItWorks/><section className="section-band bg-muted/45"><div className="site-container"><SectionHeading eyebrow="Selected projects" title="Complex workflows, made clear" description="Real automation structures from lead handling, business operations and AI-assisted support." action={<Button variant="outline" asChild><Link to="/projects">View all projects <ArrowRight/></Link></Button>}/><div className="grid gap-5 lg:grid-cols-3">{projects.slice(0,3).map(p=><ProjectCard project={p} key={p.slug}/>)}</div></div></section>
<section className="section-band"><div className="site-container"><SectionHeading eyebrow="Digital products" title="Start with a ready-made automation" description="Practical templates, blueprints and workflow packs designed for easy customization." action={<Button variant="outline" asChild><Link to="/products">Browse all products <ArrowRight/></Link></Button>}/><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{products.slice(0,4).map(p=><ProductCard product={p} key={p.slug}/>)}</div></div></section>
<Reviews/><FAQ/><FinalCTA/></>}
function TechStrip(){const tech=[[SiN8N,"n8n"],[Sparkles,"OpenAI"],[SiSupabase,"Supabase"],[SiGooglesheets,"Sheets"],[SiWhatsapp,"WhatsApp"],[SiMeta,"Meta"],[SiZapier,"Zapier"],[SiMake,"Make"]] as const;return <section className="border-y border-border bg-background py-6"><div className="site-container flex flex-wrap items-center justify-center gap-x-9 gap-y-5">{tech.map(([Icon,label])=><div key={label} className="flex items-center gap-2 text-sm font-semibold text-muted-foreground"><Icon className="h-5 w-5 text-primary"/>{label}</div>)}</div></section>}
function HowItWorks(){const steps=[["01","Understand","Map the work, delays and decisions."],["02","Design","Plan a clear, maintainable system."],["03","Connect","Join AI, APIs and trusted data."],["04","Optimize","Test realistic inputs and failures."],["05","Deploy","Launch, document and improve."]];return <section className="section-band bg-footer text-footer-foreground"><div className="site-container"><SectionHeading eyebrow="How it works" title="From repetitive task to reliable system"/><div className="grid gap-px overflow-hidden rounded-xl border border-footer-border bg-footer-border md:grid-cols-5">{steps.map(([n,t,d])=><div key={n} className="bg-footer p-6"><span className="text-sm font-bold text-primary">{n}</span><h3 className="mt-8 text-lg font-semibold">{t}</h3><p className="mt-2 text-sm leading-6 text-footer-muted">{d}</p></div>)}</div></div></section>}
const reviews=[["Arif Rahman","E-commerce founder","FlowPilot turned scattered order updates into one clear process."],["Nusrat Jahan","Marketing consultant","The lead workflow is practical and built around how our team works."],["Tanvir Ahmed","Service business owner","Customers get faster answers while we keep control when a person is needed."],["Sadia Karim","Operations manager","Daily reporting work disappeared and every request is now easier to track."]];
function Reviews(){const row=[...reviews,...reviews];return <section className="section-band bg-muted/40"><div className="site-container"><SectionHeading eyebrow="Client feedback" title="Built to make everyday work feel lighter" description="Seeded review content — ready to replace from the admin dashboard."/></div>{[false,true].map((reverse,i)=><div key={i} className="marquee-mask mb-4"><div className={`marquee-track ${reverse?"marquee-reverse":""}`}>{row.map((r,j)=><article key={`${i}-${j}`} className="mx-2 w-[340px] shrink-0 rounded-xl border border-border bg-card p-5 shadow-card"><Quote className="h-5 w-5 text-primary"/><p className="mt-3 leading-7">“{r[2]}”</p><div className="mt-4 text-sm"><strong>{r[0]}</strong><span className="ml-2 text-muted-foreground">{r[1]}</span></div></article>)}</div></div>)}</section>}
function FAQ(){return <section className="section-band"><div className="site-container grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><SectionHeading eyebrow="FAQ" title="Clear answers before we start" description="The practical details about AI, n8n, timelines, access and handoff."/><Accordion type="single" collapsible className="rounded-xl border border-border bg-card px-5">{faqs.map(([q,a],i)=><AccordionItem value={`q${i}`} key={q}><AccordionTrigger className="text-left text-base">{q}</AccordionTrigger><AccordionContent className="leading-7 text-muted-foreground">{a}</AccordionContent></AccordionItem>)}</Accordion></div></section>}
export function FinalCTA(){return <section className="px-4 pb-20"><div className="site-container rounded-xl bg-primary p-8 text-primary-foreground sm:p-14"><div className="flex flex-col justify-between gap-7 lg:flex-row lg:items-end"><div><p className="text-sm font-semibold uppercase">Next step</p><h2 className="mt-3 max-w-2xl text-4xl font-semibold sm:text-5xl">Ready to automate your business?</h2><p className="mt-4 max-w-xl text-primary-foreground/80">Tell me where the work gets stuck. I’ll help you shape a practical automation plan.</p></div><div className="flex gap-3"><Button size="lg" variant="secondary" asChild><Link to="/contact">Start a project <ArrowRight/></Link></Button><Button size="lg" variant="outline" className="border-primary-foreground/40 bg-transparent text-primary-foreground hover:bg-primary-foreground/10 hover:text-primary-foreground" asChild><Link to="/services">Explore services</Link></Button></div></div></div></section>}
